const express = require("express");
const router = express.Router();
const { query } = require("../connection/db");
const { logAction } = require('../utils/auditLogger');
const multer = require('multer');
const path = require('path');

// ── Multer config for CV uploads ──
const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, path.join(__dirname, '../upload'));
    },
    filename: function (req, file, cb) {
        const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
        cb(null, 'cv-' + uniqueSuffix + path.extname(file.originalname));
    }
});

const upload = multer({
    storage,
    fileFilter: (req, file, cb) => {
        const ext = path.extname(file.originalname).toLowerCase();
        if (ext !== '.pdf' && ext !== '.doc' && ext !== '.docx') {
            return cb(new Error('Only PDFs and Word documents are allowed for CVs'));
        }
        cb(null, true);
    }
});

// ─────────────────────────────────────────────
// GET /api/authors
// Fetch all author profiles joined with user data
// ─────────────────────────────────────────────
router.get("/", async (req, res) => {
    try {
        const sql = `
      SELECT
        ap.id          AS profile_id,
        u.id           AS user_id,
        TRIM(u.first_name || ' ' || COALESCE(u.last_name, '')) AS name,
        u.email,
        u.avatar_url,
        ap.portfolio_url,
        ap.experience,
        ap.previous_work,
        ap.cv_filename,
        ap.author_status,
        ap.created_at  AS applied_at
      FROM author_profiles ap
      JOIN users u ON ap.user_id = u.id
      ORDER BY ap.created_at DESC
    `;
        const result = await query(sql);
        res.json({ success: true, data: result.rows });
    } catch (error) {
        console.error("❌ GET /api/authors error:", error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// ─────────────────────────────────────────────
// GET /api/authors/eligible-users
// Fetch users not yet registered as authors
// ─────────────────────────────────────────────
router.get("/eligible-users", async (req, res) => {
    try {
        const sql = `
      SELECT id, first_name, last_name, email
      FROM users
      WHERE id NOT IN (SELECT user_id FROM author_profiles)
        AND role != 'Admin'
      ORDER BY first_name ASC
    `;
        const result = await query(sql);
        res.json({ success: true, data: result.rows });
    } catch (error) {
        console.error("❌ GET /api/authors/eligible-users error:", error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// ─────────────────────────────────────────────
// POST /api/authors/register
// Promote a user to author (creates profile + updates role)
// ─────────────────────────────────────────────
router.post("/register", upload.single('cv'), async (req, res) => {
    const { user_id, portfolio_url, experience, previous_work } = req.body;
    const cv_filename = req.file ? `upload/${req.file.filename}` : null;

    if (!user_id || !experience) {
        return res.status(400).json({ success: false, message: "user_id and experience are required" });
    }

    try {
        // Ensure author_profiles.id is identity column (safe guard, runs once)
        try {
            await query(`
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1 FROM pg_attribute
            WHERE attrelid = 'author_profiles'::regclass
              AND attname = 'id'
              AND attidentity != ''
          ) THEN
            ALTER TABLE author_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            PERFORM setval(
              pg_get_serial_sequence('author_profiles', 'id'),
              COALESCE(MAX(id), 0) + 1, false
            ) FROM author_profiles;
          END IF;
        END $$;
      `);
        } catch (e) {
            // Safe to ignore — table already has identity column
            console.log("Identity repair notice (safe):", e.message);
        }

        // Insert profile with 'pending' status so admin can approve/decline
        const insertSql = `
      INSERT INTO author_profiles
        (user_id, portfolio_url, experience, previous_work, cv_filename, author_status)
      VALUES ($1, $2, $3, $4, $5, 'pending')
      RETURNING *;
    `;
        await query(insertSql, [user_id, portfolio_url, experience, previous_work, cv_filename]);

        await logAction(req, 'CREATE', 'AUTHOR_PROFILE', user_id, `Registered author profile for user ${user_id}`);

        res.status(201).json({ success: true, message: "Author profile registered. Awaiting approval." });
    } catch (error) {
        console.error("❌ POST /api/authors/register error:", error);
        res.status(500).json({ success: false, message: "Database error", error: error.message });
    }
});

// ─────────────────────────────────────────────
// PUT /api/authors/approve/:id
// Approve an author — sets status to 'active' and role to 'Author'
// ─────────────────────────────────────────────
router.put("/approve/:id", async (req, res) => {
    const { id } = req.params;
    try {
        // 1. Update author_status in author_profiles
        const updateRes = await query(
            "UPDATE author_profiles SET author_status = 'active' WHERE id = $1 RETURNING user_id",
            [id]
        );

        if (updateRes.rows.length === 0) {
            return res.status(404).json({ success: false, message: "Author profile not found" });
        }

        const userId = updateRes.rows[0].user_id;

        // 2. Promote user role to 'Author'
        await query("UPDATE users SET role = 'Author' WHERE id = $1", [userId]);

        await logAction(req, 'APPROVE', 'AUTHOR_PROFILE', id, `Approved author profile ${id} for user ${userId}`);

        res.json({ success: true, message: "Author approved successfully" });
    } catch (error) {
        console.error("❌ PUT /api/authors/approve error:", error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// ─────────────────────────────────────────────
// PUT /api/authors/decline/:id
// Decline an author application — sets status to 'declined'
// ─────────────────────────────────────────────
router.put("/decline/:id", async (req, res) => {
    const { id } = req.params;
    try {
        const updateRes = await query(
            "UPDATE author_profiles SET author_status = 'declined' WHERE id = $1 RETURNING user_id",
            [id]
        );

        if (updateRes.rows.length === 0) {
            return res.status(404).json({ success: false, message: "Author profile not found" });
        }

        // Optionally reset role back to 'User' if they were already promoted
        const userId = updateRes.rows[0].user_id;
        await query("UPDATE users SET role = 'User' WHERE id = $1 AND role = 'Author'", [userId]);

        await logAction(req, 'DECLINE', 'AUTHOR_PROFILE', id, `Declined author profile ${id}`);

        res.json({ success: true, message: "Author declined successfully" });
    } catch (error) {
        console.error("❌ PUT /api/authors/decline error:", error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// ─────────────────────────────────────────────
// PUT /api/authors/status/:id
// Generic status update — set any author_status value
// ─────────────────────────────────────────────
router.put("/status/:id", async (req, res) => {
    const { id } = req.params;
    const { status } = req.body;

    const allowed = ['pending', 'active', 'declined'];
    if (!allowed.includes(status)) {
        return res.status(400).json({ success: false, message: `Status must be one of: ${allowed.join(', ')}` });
    }

    try {
        const updateRes = await query(
            "UPDATE author_profiles SET author_status = $1 WHERE id = $2 RETURNING user_id, author_status",
            [status, id]
        );

        if (updateRes.rows.length === 0) {
            return res.status(404).json({ success: false, message: "Author profile not found" });
        }

        await logAction(req, 'UPDATE', 'AUTHOR_PROFILE', id, `Set author_status to ${status}`);

        res.json({ success: true, message: `Author status updated to ${status}`, data: updateRes.rows[0] });
    } catch (error) {
        console.error("❌ PUT /api/authors/status error:", error);
        res.status(500).json({ success: false, error: error.message });
    }
});

module.exports = router;
