const express = require("express");
const router = express.Router();
const { query, DB_TYPE } = require("../connection/db");
const { logAction } = require('../utils/auditLogger');
const multer = require('multer');
const path = require('path');

const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, path.join(__dirname, '../upload'));
  },
  filename: function (req, file, cb) {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
    cb(null, 'cv-' + uniqueSuffix + path.extname(file.originalname));
  }
});

const upload = multer({
  storage: storage,
  fileFilter: (req, file, cb) => {
    const ext = path.extname(file.originalname).toLowerCase();
    if (ext !== '.pdf' && ext !== '.doc' && ext !== '.docx') {
      return cb(new Error('Only PDFs and Word documents are allowed for CVs'));
    }
    cb(null, true);
  }
});

// GET /users/roles
router.get("/users-roles", async (req, res) => {
  try {
    const allowedRoles = ['Premium', 'User', 'Author'];

    const sql = `
      SELECT 
        id,
        TRIM(first_name || ' ' || COALESCE(last_name, '')) AS name,
        first_name,
        last_name,
        email,
        role,
        status,
        location,
        avatar_url,
        created_at,
        updated_at
      FROM users
      ORDER BY created_at DESC
    `;

    const result = await query(sql);

    res.json({
      success: true,
      message: "Users fetched successfully",
      data: result.rows,
    });

  } catch (error) {
    console.error("❌ Error fetching users by role:", error);
    res.status(500).json({
      success: false,
      message: "Database error",
      error: error.message
    });
  }
});

// GET /users/eligible-authors
router.get("/eligible-authors", async (req, res) => {
  try {
    const sql = `
      SELECT id, first_name, last_name, email 
      FROM users 
      WHERE id NOT IN (SELECT user_id FROM author_profiles)
      AND role != 'Admin'
      ORDER BY first_name ASC
    `;
    const result = await query(sql);
    res.json({ success: true, data: result.rows });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// POST /create-author
router.post("/create-author", upload.single('cv'), async (req, res) => {
  const { user_id, portfolio_url, experience, previous_work } = req.body;
  const cv_filename = req.file ? `upload/${req.file.filename}` : null;

  try {
    // 0. Emergency Fix: Ensure ID is auto-incrementing (if user missed it in pgAdmin)
    try {
      await query(`
        DO $$ 
        BEGIN 
          IF NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'author_profiles'::regclass AND attname = 'id' AND attidentity != '') THEN
            ALTER TABLE author_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            -- Reset sequence to handle existing data if any
            PERFORM setval(pg_get_serial_sequence('author_profiles', 'id'), COALESCE(MAX(id), 0) + 1, false) FROM author_profiles;
          END IF;
        END $$;
      `);
    } catch (e) {
      console.log("Repair notice (safe to ignore if already fixed):", e.message);
    }

    // 1. Create Author Profile
    const authorSql = `
      INSERT INTO author_profiles (user_id, portfolio_url, experience, previous_work, cv_filename, author_status)
      VALUES ($1, $2, $3, $4, $5, 'active')
      RETURNING *;
    `;
    await query(authorSql, [user_id, portfolio_url, experience, previous_work, cv_filename]);

    // 2. Update User Role
    await query("UPDATE users SET role = 'Author' WHERE id = $1", [user_id]);

    await logAction(req, 'CREATE', 'AUTHOR_PROFILE', user_id, `Created author profile for user ${user_id}`);

    res.status(201).json({ success: true, message: "Author profile created successfully" });
  } catch (error) {
    console.error("Error creating author:", error);
    res.status(500).json({ success: false, message: "Database error", error: error.message });
  }
});




router.put("/toggle-status/:id", async (req, res) => {
  const { id } = req.params;

  try {
    // 1. Get current status
    const userResult = await query(
      "SELECT status FROM users WHERE id = $1",
      [id]
    );

    if (userResult.rows.length === 0) {
      return res.status(404).json({
        success: false,
        message: "User not found",
      });
    }

    const currentStatus = userResult.rows[0].status;
    const newStatus = currentStatus === "Active" ? "Banned" : "Active";

    // 2. Update status
    await query(
      `
      UPDATE users
      SET status = $1,
          updated_at = CURRENT_TIMESTAMP
      WHERE id = $2
      `,
      [newStatus, id]
    );

    await logAction(req, 'UPDATE', 'USER', id, `Changed user status to ${newStatus}`);

    res.status(200).json({
      success: true,
      message: `User status updated to ${newStatus}`,
      status: newStatus,
    });

  } catch (error) {
    console.error("Error toggling user status:", error);
    res.status(500).json({
      success: false,
      message: "Server error",
    });
  }
});

module.exports = router;
